# Generated by Django 4.2.30 on 2026-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_ip', models.GenericIPAddressField()),
                ('master_ip', models.GenericIPAddressField()),
                ('slave_ip', models.GenericIPAddressField()),
                ('interface', models.CharField(max_length=20)),
                ('master_priority', models.IntegerField(default=100)),
                ('slave_priority', models.IntegerField(default=90)),
            ],
        ),
    ]
